spring:
  application:
    name: stockverse-backend

  datasource:
    url: jdbc:mysql://localhost:3306/pp_stockverse_ai
    username: root
    password: pawan@08
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080